CREATE TABLE users (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  telegram_id TEXT UNIQUE NOT NULL,
  username TEXT,
  damper_id TEXT UNIQUE NOT NULL,
  role TEXT NOT NULL DEFAULT 'PLAYER',
  created_at INTEGER NOT NULL
);

CREATE TABLE wallets (
  user_id INTEGER PRIMARY KEY,
  balance INTEGER NOT NULL DEFAULT 500,
  FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE xp (
  user_id INTEGER PRIMARY KEY,
  damper_xp INTEGER NOT NULL DEFAULT 0,
  level INTEGER NOT NULL DEFAULT 1,
  rpg_xp INTEGER NOT NULL DEFAULT 0,
  rpg_level INTEGER NOT NULL DEFAULT 1,
  FOREIGN KEY (user_id) REFERENCES users(id)
);
