import { newMinesGame, openMine, cashout } from './games/mines.js';
import { nextQuestion, checkBrainAnswer, brainReward } from './games/brain-service.js';

const BANNER_FILE_ID='AgACAgQAAxkBAAMIaqrLcsPcHMx7oPIUstU4FEnr7UYAAuEYaxsFs1lRZUeHg_eeON4BAAMCAAN5AAM9BA';
const MEME='@nah_idmeme', UPDATES='@Updamper_bot', MIN=50, now=()=>Math.floor(Date.now()/1000);
const kb=inline_keyboard=>({inline_keyboard});
async function tg(env,method,body){const r=await fetch(`https://api.telegram.org/bot${env.TELEGRAM_BOT_TOKEN}/${method}`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)});return r.json();}
const send=(env,chat_id,text,reply_markup)=>tg(env,'sendMessage',{chat_id,text,parse_mode:'Markdown',...(reply_markup?{reply_markup}:{})});
const edit=(env,chat_id,message_id,text,reply_markup)=>tg(env,'editMessageText',{chat_id,message_id,text,parse_mode:'Markdown',...(reply_markup?{reply_markup}:{})});
const photo=(env,chat_id,caption,reply_markup)=>tg(env,'sendPhoto',{chat_id,photo:BANNER_FILE_ID,caption,parse_mode:'Markdown',...(reply_markup?{reply_markup}:{})});
const ack=(env,id,text='')=>tg(env,'answerCallbackQuery',{callback_query_id:id,text});
const back=()=>kb([[{text:'⬅️ BACK',callback_data:'menu_main'}]]);
const main=()=>kb([[{text:'🎮 GAMES',callback_data:'menu_games'},{text:'💰 ECONOMY',callback_data:'menu_economy'}],[{text:'⚔️ RPG',callback_data:'menu_rpg'},{text:'🛒 SHOP',callback_data:'menu_shop'}],[{text:'🗃️ VAULT',callback_data:'menu_vault'},{text:'📊 LEADERBOARD',callback_data:'menu_leaderboard'}],[{text:'👤 PROFILE',callback_data:'menu_profile'},{text:'❓ HELP',callback_data:'menu_help'}]]);
const games=()=>kb([[{text:'🪙 COIN FLIP',callback_data:'game_coin'},{text:'🎲 DICE DUEL',callback_data:'game_dice'}],[{text:'💣 MINES',callback_data:'game_mines'},{text:'🎰 SLOTS',callback_data:'game_slots'}],[{text:'⚽ PENALTY',callback_data:'game_penalty'},{text:'🏁 VIRTUAL RACE',callback_data:'game_race'}],[{text:'🧠 BRAIN',callback_data:'game_brain'},{text:'⚡ REACTION',callback_data:'game_reaction'}],[{text:'⬅️ BACK',callback_data:'menu_main'}]]);
const stake=(g,i)=>kb([[{text:`${i} 50`,callback_data:`stake:${g}:50`},{text:`${i} 100`,callback_data:`stake:${g}:100`}],[{text:`${i} 250`,callback_data:`stake:${g}:250`}],[{text:'⬅️ BACK',callback_data:'menu_games'}]]);
const join=()=>kb([[{text:'🧠 JOIN MEME CHANNEL',url:'https://t.me/nah_idmeme'}],[{text:'🔥 JOIN UPDATES CHANNEL',url:'https://t.me/Updamper_bot'}],[{text:'✅ CHECK MEMBERSHIP',callback_data:'check_membership'}]]);
async function member(env,ch,id){const r=await tg(env,'getChatMember',{chat_id:ch,user_id:id});return !!(r.ok&&['creator','administrator','member'].includes(r.result?.status));}
async function access(env,id){if(env.OWNER_TELEGRAM_ID&&String(env.OWNER_TELEGRAM_ID)===String(id))return true;return member(env,MEME,id)&&member(env,UPDATES,id);}
async function user(env,id){return env.DB.prepare('SELECT u.*,w.balance,x.damper_xp,x.level,x.rpg_xp,x.rpg_level FROM users u LEFT JOIN wallets w ON w.user_id=u.id LEFT JOIN xp x ON x.user_id=u.id WHERE u.telegram_id=?').bind(String(id)).first();}
async function account(env,from){let u=await user(env,from.id);if(u)return u;const owner=env.OWNER_TELEGRAM_ID&&String(env.OWNER_TELEGRAM_ID)===String(from.id);let did;for(let i=0;i<50;i++){const candidate=String(Math.floor(10000+Math.random()*90000));if(!(await env.DB.prepare('SELECT id FROM users WHERE damper_id=?').bind(candidate).first())){did=candidate;break;}}if(!did)throw Error('Damper ID allocation failed');await env.DB.prepare('INSERT INTO users(telegram_id,username,damper_id,role,created_at) VALUES(?,?,?,?,?)').bind(String(from.id),from.username||null,did,owner?'OWNER':'PLAYER',now()).run();u=await user(env,from.id);await env.DB.prepare('INSERT OR IGNORE INTO wallets(user_id,balance) VALUES(?,500)').bind(u.id).run();await env.DB.prepare('INSERT OR IGNORE INTO xp(user_id,damper_xp,level,rpg_xp,rpg_level) VALUES(?,0,1,0,1)').bind(u.id).run();await env.DB.prepare('INSERT OR IGNORE INTO stats(user_id) VALUES(?)').bind(u.id).run();return user(env,from.id);}
async function wallet(env,id,delta){const r=await env.DB.prepare('UPDATE wallets SET balance=balance+? WHERE user_id=? AND balance+?>=?').bind(delta,id,delta,0).run();if(!r.meta?.changes)throw Error('INSUFFICIENT');}
async function record(env,u,type,outcome,stake,payout,xp){await env.DB.prepare('UPDATE stats SET games_played=games_played+1,games_won=games_won+?,games_lost=games_lost+?,wager_games=wager_games+?,total_staked=total_staked+?,total_won=total_won+?,total_lost=total_lost+?,biggest_stake=MAX(biggest_stake,?),biggest_payout=MAX(biggest_payout,?) WHERE user_id=?').bind(outcome==='WIN'?1:0,outcome==='LOSS'?1:0,stake>0?1:0,stake,Math.max(0,payout-stake),Math.max(0,stake-payout),stake,payout,u.id).run();await env.DB.prepare('INSERT INTO game_results(user_id,game_type,outcome,stake,payout,xp,created_at) VALUES(?,?,?,?,?,?,?)').bind(u.id,type,outcome,stake,payout,xp,now()).run();}
async function startWager(env,chat,u,type,amount,state={}){const s=Number(amount);if(!Number.isInteger(s)||s<MIN)return send(env,chat,'⚠️ Minimum wager is *50* Damper Coins.');if(s>(u.balance||0))return send(env,chat,'❌ Insufficient Damper Coins.');const active=await env.DB.prepare('SELECT id FROM game_sessions WHERE player_id=? AND result IS NULL AND expires_at>? LIMIT 1').bind(u.id,now()).first();if(active)return send(env,chat,'⏳ You already have an active game.');const id=`tg_${crypto.randomUUID().replaceAll('-','').slice(0,12)}`;await wallet(env,u.id,-s);await env.DB.prepare('INSERT INTO game_sessions(id,game_type,chat_id,player_id,state,stake,expires_at,created_at) VALUES(?,?,?,?,?,?,?,?)').bind(id,type,String(chat),u.id,JSON.stringify(state),s,now()+900,now()).run();return id;}
function dice(){const a=1+Math.floor(Math.random()*6),b=1+Math.floor(Math.random()*6),o=a>b?'WIN':a===b?'DRAW':'LOSS';return {o,m:o==='WIN'?1.8:o==='DRAW'?1:0,xp:o==='WIN'?10:o==='DRAW'?4:2,text:`🎲 *DICE DUEL*\n\nYou: ${a}\nBot: ${b}\n\n${o==='WIN'?'You win.':o==='DRAW'?'Draw — stake returned.':'You lose.'}`};}
async function settle(env,chat,u,sid,type,r){const s=await env.DB.prepare('SELECT * FROM game_sessions WHERE id=? AND player_id=?').bind(sid,u.id).first();if(!s||s.reward_applied)return send(env,chat,'⌛ This game session has ended.');const payout=Math.floor(s.stake*r.m);if(payout)await wallet(env,u.id,payout);await record(env,u,type,r.o,s.stake,payout,r.xp);await env.DB.prepare('UPDATE game_sessions SET result=?,reward_applied=1 WHERE id=? AND reward_applied=0').bind(JSON.stringify(r),sid).run();return send(env,chat,`${r.text}\n\n${payout?`💰 Payout: *${payout}*`:`💸 Lost: *${s.stake}*`}\n✨ +${r.xp} XP`);}
async function command(env,msg,text){const c=String(text).trim().split(/\s+/)[0].toLowerCase(),chat=msg.chat.id;if(c==='/start'){if(!(await access(env,msg.from.id)))return photo(env,chat,'🔥 *THE DAMPER_BOT V2*\n\nJoin both official channels, then check membership.',join());const u=await account(env,msg.from);return photo(env,chat,`🔥 *THE DAMPER_BOT V2*\n\n🆔 Damper ID: \`${u.damper_id}\`\n💰 ${u.balance||500} Coins\n⭐ Level ${u.level||1}`,main());}if(!(await access(env,msg.from.id)))return send(env,chat,'🔒 Access locked. Use /start to verify membership.',join());const u=await account(env,msg.from);if(c==='/menu')return send(env,chat,'🔥 *THE DAMPER_BOT V2*',main());if(c==='/games')return send(env,chat,'🎮 *GAMES*',games());if(c==='/balance')return send(env,chat,`💰 *BALANCE*\n\n🪙 ${u.balance||0}\n⭐ Level ${u.level||1}\n✨ XP ${u.damper_xp||0}`);if(c==='/profile')return send(env,chat,`👤 *PROFILE*\n\nUsername: ${u.username?`@${u.username}`:'—'}\n🆔 Damper ID: \`${u.damper_id}\`\n💰 Coins: ${u.balance||0}\n⭐ Level: ${u.level||1}\n✨ XP: ${u.damper_xp||0}`,back());if(c==='/ping')return send(env,chat,'🏓 Pong! V2 is alive.');if(c==='/dice'){const n=Number(text.split(/\s+/).pop());const sid=await startWager(env,chat,u,'DICE_DUEL',n);if(!sid)return;return settle(env,chat,u,sid,'DICE_DUEL',dice());}return send(env,chat,'🤔 Try /menu or /help.');}
async function callback(env,q){const chat=q.message?.chat?.id,mid=q.message?.message_id,d=q.data||'';await ack(env,q.id);if(d==='check_membership'){const ok=await access(env,q.from.id);return ok?edit(env,chat,mid,'✅ *MEMBERSHIP VERIFIED*\n\nChoose your destination.',main()):edit(env,chat,mid,'❌ Join both channels first.',join());}if(!(await access(env,q.from.id)))return edit(env,chat,mid,'🔒 *ACCESS LOCKED*\n\nJoin both channels, then check membership.',join());const u=await account(env,q.from);if(d==='menu_main')return edit(env,chat,mid,'🔥 *THE DAMPER_BOT V2*',main());if(d==='menu_games')return edit(env,chat,mid,'🎮 *GAMES*\n\nMinimum wager: 50 Coins.',games());if(d==='game_dice')return edit(env,chat,mid,'🎲 *DICE DUEL*\n\nChoose your wager.',stake('dice','🎲'));if(d==='game_slots')return edit(env,chat,mid,'🎰 *SLOTS*\n\nChoose your wager.',stake('slots','🎰'));if(d==='game_race')return edit(env,chat,mid,'🏁 *VIRTUAL RACE*\n\nChoose your wager.',stake('race','🏁'));if(d==='game_mines')return edit(env,chat,mid,'💣 *MINES*\n\n12 tiles / 3 mines.\nChoose your wager.',stake('mines','💣'));if(d==='game_brain')return edit(env,chat,mid,'🧠 *BRAIN*\n\nBrain questions are being connected.',back());if(d==='game_reaction')return edit(env,chat,mid,'⚡ *REACTION*\n\nReaction games are being connected.',back());if(d.startsWith('stake:')){const [,g,s]=d.split(':');const type={dice:'DICE_DUEL',slots:'SLOTS',race:'RACE'}[g];if(type){const sid=await startWager(env,chat,u,type,Number(s));if(!sid)return;return settle(env,chat,u,sid,type,dice());}return send(env,chat,'💣 Mines interactive board is next.');}return send(env,chat,'That button is not available yet.',back());}
export default {async fetch(request,env){try{const url=new URL(request.url);if(url.pathname==='/'&&request.method==='GET'){const tables=await env.DB.prepare("SELECT name FROM sqlite_master WHERE type='table' ORDER BY name").all();return Response.json({status:'online',database:'connected',telegram:env.TELEGRAM_BOT_TOKEN?'configured':'missing',tables:tables.results||[]});}if(url.pathname==='/telegram/webhook'&&request.method==='POST'){const update=await request.json();if(update.callback_query)await callback(env,update.callback_query);else if(update.message?.text)await command(env,update.message,update.message.text);return new Response('OK');}return new Response('OK');}catch(e){console.error(e);return new Response('OK');}}};
